application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /style.css 
  static_files: style.css
  upload: style.css 
- url: /.*
  script: falkfood.application